# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Install pods"
  lane :Pods do
    pods 
  end

  desc "Install pact"
  lane :Install_pact do
    install_pact
  end

  desc "Run pacts test"
  lane :Pact_tests do
    run_tests(workspace: "PactConsumerSwiftExample.xcworkspace"
        scheme: "PactConsumerSwiftExampleForTests",
        device: "iPhone 12"
     )
  end

end

####### Definitions

def pods
  sh("pod repo update")
  sh("pod install")
end

def install_pact
  sh("gem install pact-mock_service")
end

