name: Pact CI
#Workflow triggered on pushes
on:
  push:
    branches: main
# Run the next jobs
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install Bundle
      run: cd PactConsumerSwiftExample
           \ bundle install
      
    - name: Install pods
      run: bundle exec fastlane Pods
      
    - name: Install pact stand alone
      run: bundle exec fastlane Install_pact
      
    - name: Run pact test
      run: bundle exec faslane Pact_tests
