name: Pact CI
#Workflow triggered on pushes
on:
  push:
    branches: main
# Run the next jobs
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    
    - name: Install Bundle
      run: |
          cd PactConsumerSwiftExample
          bundle install
      
    - name: Install pods
      run: |
          cd PactConsumerSwiftExample
          bundle exec fastlane Pods --verbose
      
    - name: Install pact stand alone
      run: |
          cd PactConsumerSwiftExample
          bundle exec fastlane Install_pact --verbose
      
    - name: Run pact test
      run: xcodebuild clean build test -workspace PactConsumerSwiftExample/PactConsumerSwiftExample.xcworkspace -scheme "PactConsumerSwiftExampleForTests" -destination "platform=iOS Simulator,name=iPhone 12,,OS=14.4"

